spring:
  flyway:
    default-schema: ${APP_DB_SCHEMA:public}
    create-schemas: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      schema: ${APP_DB_SCHEMA:public}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        default_schema: ${APP_DB_SCHEMA:public}

